version : '3.8'

services:
  mariadb:
    image: mariadb:inception
    container_name : mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
    - "3306"
    networks:
      - inception-network
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress:inception
    container_name : wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    expose:
    - "9000"
    networks:
      - inception-network
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:inception
    container_name : nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    networks:
      - inception-network
    ports:
     - "443:443"
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - .env
    restart: always

volumes:
  db_vol:
    name: 1_db
    driver: local
    driver_opts:
      device: /Users/jaehejun/desktop/inception/1_db
      o: bind
      type: none
  wp_vol:
    name: 2_wp
    driver: local
    driver_opts:
      device: /Users/jaehejun/desktop/inception/2_wp
      o: bind
      type: none

networks:
  inception-network:
    driver: bridge